spring.application.name=comicverse-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/comicverse
spring.datasource.username=postgres
spring.datasource.password=Zoro

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true